# -*- coding: utf-8 -*-
"""taş kağıt makas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cNNb2H4MhSEyz2Kz294DlRXLgyyOYjYr
"""

import random
user_point=0
comp_point=0
a=["taş","kağıt","makas"]

while user_point<3 and comp_point<3:
 user=input("taş, kağıt ya da makas")
 while user != "taş" and user != "makas" and user != "kağıt":
    user=input("yanlış girdiniz, lütfen geçerli cevabı giriniz:")
 comp=random.choice(a)
 print("sen:",user,"computer:",comp)

 if user==comp:
   print("berabere")

 elif user=="taş":
   if comp=="kağıt":
     comp_point=comp_point+1
     print("kaybettin")
   elif comp=="makas":
      user_point=user_point+1
      print("kazandın")
   print("senin puanın: ",user_point,"computer: ",comp_point)

 elif user=="kağıt":
   if comp=="makas":
      comp_point=comp_point+1
      print("kaybettin")
   elif comp=="taş":
     user_point=user_point+1
     print("kazandın")
   print("senin puanın: ",user_point,"computer: ",comp_point)

 elif user=="makas":
  if comp=="taş":
     comp_point=comp_point+1
     print("kaybettin")
  elif comp=="kağıt":
    user_point=user_point+1
    print("kazandın")    
  print("senin puanın: ",user_point,"computer: ",comp_point)

if user_point==3:
  print("oyunu kazandın")
elif comp_point==3:
  print("oyunu kaybettin")